baseURL = "https://pedantic-sinoussi-974ee3.netlify.com/"
languageCode = "en-us"
title = "Open Cybersecurity Alliance"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 20 # number of sponsors that will show on sponsor page at a time
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/Favicon.png"
  description = "A simple, quick, easy-to-modify project website."
  facebook = "https://www.facebook.com/oasis.open"
  twitter = "https://twitter.com/OASISopen"
  instagram = ""
  youtube = ""
  github = "https://github.com/oasis-open-projects"
  gitlab = ""
  linkedin = "https://www.linkedin.com/company/oasis/"
  mastodon = ""
  logo = "/images/OCA_logo.png"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/cyber_background.jpg"
  recent_posts_number = 1
  mailing_list_subscribe = "mailto:op-admin@oasis-open.org"
  custom_css = ["css/custom.css"]
  mainSections = ["news", "sponsors"]
